spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test2?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=GMT&characterEncoding=UTF-8
    username: ${USER}
    password: ${PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  thymeleaf:
    cache: false
  mvc:
    format:
      date: yyyy-MM-dd
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${CORREO}
    password: ${PASS_CORREO}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            required: true
            enable: true
          ssl:
            trust: smtp.gmail.com
logging:
  level:
    org:
      springframework:
        web: debug
my:
  property: 
